# Generated by Django 4.1.5 on 2023-11-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="notification",
        ),
    ]
