# Generated by Django 4.1.5 on 2023-11-27 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_alter_account_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
