# Generated by Django 4.1.5 on 2023-11-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_alter_account_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="App.account",
            ),
        ),
    ]
