# Generated by Django 4.1.5 on 2023-11-27 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0007_alter_block_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="send_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
